### ISSUE TITLE
getting error "frozen importlib._bootstrap" when running in Anaconda Spyder

### ISSUE THREAD

**Issue by kamrapooja** [legolas123/cv-tricks.com#13]
Hi,
I am getting error "frozen importlib._bootstrap>(219)_call_with_frames_removed()" after line 93.
93 line is class DataSets(object):
I am new in Deep Learning as well as in Tensorflow.
Please help to resolve this issue

**Comment by sankit1** [comment]
Looks like your setup related issue. Please reopen if still not resolved. Also, please provide exact steps to replicate.
