### ISSUE TITLE
 Where could I get the code for passing an image to a CNN Cifar10 TensorFlow Model and getting the result in terms of prediction scores

### ISSUE THREAD

**Issue by frajos100** [legolas123/cv-tricks.com#16]
Where could I get the code for passing an image to a CNN Cifar10 TensorFlow Model and getting the result in terms of prediction scores 
I had Build the CNN  Cifar10 TensorFlow Model following the tutorial at 
https://www.tensorflow.org/tutorials/deep_cnn 
Code:
https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10

**Comment by sankit1** [comment]
Hi, 
   Please raise bugs which are relevant to the code of this repository. For, these kinds of requests please send an email to hello@cv-tricks.com. Thank you for maintaining the sanity :)
