### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead

### ISSUE THREAD

**Issue by ninjacoder123** [legolas123/cv-tricks.com#2]
In the folder, Tensorflow-tutorials/Tensorflow-slim-run-prediction when I run python run_inference_on_v3.py http://cv-tricks.com/wp-content/uploads/2017/03/pexels-photo-280207.jpeg
To run the prediction for the model inception_v3 as per the blog post http://cv-tricks.com/tensorflow-tutorial/understanding-alexnet-resnet-squeezenetand-running-on-tensorflow/, I get the following error: 

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
**Tensorflow version**: 1.1

**Comment by sankit1** [comment]
Tensorflow release 1.0 changed the signature of the function concat as per the release log. 
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md
I have fixed the networks. It should work fine.
