### ISSUE TITLE
cannot connect to X server error

### ISSUE THREAD

**Issue by shantanuo** [legolas123/cv-tricks.com#23]
Getting an error while running the code.

python3 run_pose.py --input sample.jpg --proto pose/mpi/pose_deploy_linevec_faster_4_stages.prototxt --model pose/mpi/pose_iter_160000.caffemodel --dataset MPI
time is  2.5539000034332275
: cannot connect to X server

**Comment by sankit1** [comment]
The error means that your computer doesn't have a display. Either add a monitor or comment the imshow statements in the code. Please reopen if more help is needed.

**Comment by shantanuo** [comment]
Thanks for your reply. It worked as expected after commenting the imshow statements. Your blog is awesome by the way. I learned a lot.
