### ISSUE TITLE
Help porting to Cpp

### ISSUE THREAD

**Issue by rpelissier** [legolas123/cv-tricks.com#25]
Hello,
Thank you for sharing this excellent work. I am trying to port the Crop Layer to cpp.
I am not very familiar with Python, can you elaborate on the meaning of this Python operation :
````python
return [inputs[0][:,:,self.ystart:self.yend,self.xstart:self.xend]]
````
Is `inputs[0]` a 4D cube and I want to take only the sub-cube delimited by x and y indexes?
Cheers,
Renaud

**Comment by legolas123** [comment]
Yes you are correct. inputs[0] is a 4D tensor. And the operation you mentioned is slicing in the last two dimensions. So if the inputs[0] shape is n,c,h,w, then that operation's output will be n,c,h_sliced,w_sliced.
