### ISSUE TITLE
Using real valued downsample

### ISSUE THREAD

**Issue by huangqiu15444** [legolas123/cv-tricks.com#29]
What is the meaning of "Using real valued downsample"?

**Comment by legolas123** [comment]
Normally xnornet uses binary convolution for the bypass connection in the resnet block. By "real valued downsample", I mean that it is using float32 convolution in bypass connection.
Give me sometime. I will add a network visualization to make things clear.
Thanks

**Comment by legolas123** [comment]
Please pull in the latest code. Have fixed a bug which was giving higher accuracy before.
