### ISSUE TITLE
how to restore and evaluate the trained net?

### ISSUE THREAD

**Issue by ldenoue** [legolas123/cv-tricks.com#3]
Could you add a way to save the model?
Also, could you add a file to load the saved model and infer the prediction on a test image?

Laurent

**Comment by Hatsunespica** [comment]
here https://stackoverflow.com/questions/33759623/tensorflow-how-to-save-restore-a-model
the second answer
you can insert your load code into the "optimize" function before the for loop in train.py

**Comment by sankit1** [comment]
Updated the code and added a way to save and restore model. Use predict.py to predict on your own images.

**Comment by ldenoue** [comment]
Awesome thank you!
