### ISSUE TITLE
hey am using ur code on python 2.7 but am getting following error 

### ISSUE THREAD

**Issue by pratikpadamwar** [legolas123/cv-tricks.com#6]
my issue is in imagnet.py where my tring to access url am getting the url error as follows 
   filename, _ = urllib.urlretrieve(synset_url,"imagenet_lsvrc_2015_synsets.txt")
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
and my code is 
  base_url = 'https://github.com/tensorflow/models/tree/master/research/inception/inception/data'
  synset_url = 'https://github.com/tensorflow/models/tree/master/research/inception/inception/data/imagenet_lsvrc_2015_synsets.txt'.format(base_url)
  synset_to_human_url = 'https://github.com/tensorflow/models/tree/master/research/inception/inception/data/imagenet_metadata.txt'.format(base_url)

  filename, _ = urllib.urlretrieve(synset_url,"imagenet_lsvrc_2015_synsets.txt")
  synset_list = [s.strip() for s in open(filename).readlines()]
  num_synsets_in_ilsvrc = len(synset_list)
  assert num_synsets_in_ilsvrc == 1000

  filename, _ = urllib.urlretrieve(synset_to_human_url,"imagenet_metadata.txt")
  synset_to_human_list = open(filename).readlines()
  num_synsets_in_all_imagenet = len(synset_to_human_list)
  assert num_synsets_in_all_imagenet == 21842
please help me am totally frustraed bu this issue

**Comment by sankit1** [comment]
It appears that you are using urls from previous version. Please try to use the imagenet.py provided in this repository. I have tested with python 2.7 and tensorflow 1.3. I can run 
`python run_inference_on_v1.py https://pbs.twimg.com/media/B5B9ZsvIgAATiC6.jpg`
 and see the prediction on my image.

**Comment by pratikpadamwar** [comment]
which repositry  plesae send me the link

**Comment by pratikpadamwar** [comment]
hey ankit which repository u re talking about can please tell me in detail

**Comment by pratikpadamwar** [comment]
base_url = 'https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/'
  synset_url = '{}/imagenet_lsvrc_2015_synsets.txt'.format(base_url)
  synset_to_human_url = '{}/imagenet_metadata.txt'.format(base_url) 
actuall i tried this one first am gettng same error thats why i take that url which is working in browser but then also it is giving same error

**Comment by sankit1** [comment]
Try this: 
1. Open terminal and run following code.
`mkdir test`
`git clone https://github.com/sankit1/cv-tricks.com.git`
`cd cv-tricks.com/Tensorflow-tutorials/Tensorflow-slim-run-prediction/slim_pretrained`
`sh download_extract_v1.sh`
`cd ..`
`python run_inference_on_v1.py https://pbs.twimg.com/media/B5B9ZsvIgAATiC6.jpg`

**Comment by pratikpadamwar** [comment]
for tutorial:tutorial2 image classifier
hey ankit am using your code for 7 classes but when at the time of training
it showing only train images=1654 even though i have 4000 images why it is
so
2> is mandatory that in testing_data we have to make same folder that we
have given in traing_data whty it is so cant i predict image from anywhere
when am tring to do that is not predicting the image at all
what to do real all the images changes ihave made is
1> calses in train.py to 7 classes and
mode name i changed
3> in predict.py i changed classes name and the number np.zeros(1,7)
is there anything i have to change
4> when am predicting it is giving ans in e-01 why it is so and how to
overcome that one to get the values in 0.9 format please help me
