### ISSUE TITLE
not able to retrieve the image for prediction

### ISSUE THREAD

**Issue by ankitjha-ai** [legolas123/cv-tricks.com#9]
I am not able to get the image_path correctly.
The output is showing ---------------------**list index out of range** by running your code predict.py
`dir_path = os.path.dirname(os.path.abspath(__file__))
image_path=sys.argv[1] `

due to which `image = cv2.resize(image, (image_size, image_size),0,0, cv2.INTER_LINEAR)` is also not working.

output of dir_path **D:\WORKSPACE\Deep_learning\others\cv_tricks.com_new\cv-tricks.com\Tensorflow-tutorials\tutorial-2-image-classifier**
output of image_path **D:/WORKSPACE/Deep_learning/others/cv_tricks.com_new/cv-tricks.com/Tensorflow-tutorials/tutorial-2-image-classifier/predict.py**

how can this be solved?

**Comment by sankit1** [comment]
You need to pass the image for prediction:
python predict.py testing_data/cats/cat.1110.jpg
